/**
 * Curated Preset Themes
 * Complete theme configurations with harmonious combinations of mode, colors, radius, fonts, and syntax themes.
 */

import type { ThemePreset } from "./types";

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "default-zinc",
    name: "RepoDeck Clean",
    description:
      "Modern zinc backdrop with vibrant blue accents and balanced geometry.",
    mode: "dark",
    settings: {
      accentColor: "blue",
      baseColor: "zinc",
      radius: 0.5,
      font: "geist-sans",
      codeTheme: "github",
      transparentCodeBg: true,
    },
    previewColors: {
      primary: "#3b82f6",
      background: "#09090b",
      card: "#18181b",
      foreground: "#fafafa",
      border: "#27272a",
      muted: "#a1a1aa",
      badgeBg: "#27272a",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    description:
      "Inspired by GitHub's developer UI with cool slate tones and sky accents.",
    mode: "dark",
    settings: {
      accentColor: "sky",
      baseColor: "slate",
      radius: 0.375,
      font: "inter",
      codeTheme: "github",
    },
    previewColors: {
      primary: "#0ea5e9",
      background: "#020617",
      card: "#0f172a",
      foreground: "#f8fafc",
      border: "#1e293b",
      muted: "#94a3b8",
      badgeBg: "#1e293b",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description:
      "Deep indigo night aesthetic with violet highlights and monospace crispness.",
    mode: "dark",
    settings: {
      accentColor: "violet",
      baseColor: "midnight",
      radius: 0.5,
      font: "jetbrains-mono",
      codeTheme: "tokyo-night",
    },
    previewColors: {
      primary: "#8b5cf6",
      background: "#0f172a",
      card: "#1e293b",
      foreground: "#e2e8f0",
      border: "#334155",
      muted: "#94a3b8",
      badgeBg: "#292e42",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    description:
      "Warm pastel mauve base with soothing rose accent and soft rounded curves.",
    mode: "dark",
    settings: {
      accentColor: "rose",
      baseColor: "mauve",
      radius: 0.75,
      font: "figtree",
      codeTheme: "catppuccin",
    },
    previewColors: {
      primary: "#f43f5e",
      background: "#18111b",
      card: "#261c2b",
      foreground: "#f5e0dc",
      border: "#3b2d42",
      muted: "#cdd6f4",
      badgeBg: "#312338",
    },
  },
  {
    id: "emerald-forest",
    name: "Emerald Forest",
    description:
      "Organic sage tones paired with fresh emerald accents and Outfit typography.",
    mode: "dark",
    settings: {
      accentColor: "emerald",
      baseColor: "sage",
      radius: 0.5,
      font: "outfit",
      codeTheme: "everforest",
    },
    previewColors: {
      primary: "#10b981",
      background: "#0d1712",
      card: "#14241c",
      foreground: "#ecfdf5",
      border: "#203a2e",
      muted: "#a7f3d0",
      badgeBg: "#1b3327",
    },
  },
  {
    id: "nordic-frost",
    name: "Nordic Frost",
    description:
      "Arctic cold palette with arctic cyan accents and clean neutral slate geometry.",
    mode: "dark",
    settings: {
      accentColor: "cyan",
      baseColor: "nordic",
      radius: 0.5,
      font: "inter",
      codeTheme: "nord",
    },
    previewColors: {
      primary: "#06b6d4",
      background: "#08101a",
      card: "#101d2e",
      foreground: "#f0f9ff",
      border: "#1c324f",
      muted: "#bae6fd",
      badgeBg: "#17283c",
    },
  },
  {
    id: "warm-sandstone",
    name: "Warm Sandstone",
    description:
      "Earthy desert sand tone with warm amber accents and refined typography.",
    mode: "dark",
    settings: {
      accentColor: "amber",
      baseColor: "sand",
      radius: 0.5,
      font: "raleway",
      codeTheme: "gruvbox",
    },
    previewColors: {
      primary: "#f59e0b",
      background: "#171410",
      card: "#262019",
      foreground: "#fef3c7",
      border: "#3d3429",
      muted: "#fde68a",
      badgeBg: "#332a21",
    },
  },
  {
    id: "cyber-neon",
    name: "Cyberpunk Neon",
    description:
      "High-contrast dark obsidian background with electric fuchsia highlights.",
    mode: "dark",
    settings: {
      accentColor: "fuchsia",
      baseColor: "obsidian",
      radius: 0.25,
      font: "jetbrains-mono",
      codeTheme: "synthwave-84",
    },
    previewColors: {
      primary: "#d946ef",
      background: "#08080a",
      card: "#141418",
      foreground: "#fae8ff",
      border: "#2d1b38",
      muted: "#f5d0fe",
      badgeBg: "#23162b",
    },
  },
  {
    id: "minimal-sharp",
    name: "Minimal Sharp",
    description:
      "Zero border-radius industrial geometry with neutral grays and pure focus.",
    mode: "dark",
    settings: {
      accentColor: "blue",
      baseColor: "obsidian",
      radius: 0,
      font: "roboto",
      codeTheme: "vesper",
    },
    previewColors: {
      primary: "#3b82f6",
      background: "#121212",
      card: "#1c1c1c",
      foreground: "#ededed",
      border: "#333333",
      muted: "#a0a0a0",
      badgeBg: "#282828",
    },
  },
  {
    id: "dracula-twilight",
    name: "Dracula Twilight",
    description:
      "Gothic dark purple backdrop with vivid electric purple accents.",
    mode: "dark",
    settings: {
      accentColor: "purple",
      baseColor: "dusk",
      radius: 0.5,
      font: "jetbrains-mono",
      codeTheme: "dracula",
    },
    previewColors: {
      primary: "#a855f7",
      background: "#140e1f",
      card: "#201730",
      foreground: "#f3e8ff",
      border: "#35254f",
      muted: "#e9d5ff",
      badgeBg: "#2a1e40",
    },
  },
  {
    id: "github-light",
    name: "GitHub Light",
    description:
      "Crisp white canvas with classic blue accents and structured readability.",
    mode: "light",
    settings: {
      accentColor: "blue",
      baseColor: "slate",
      radius: 0.375,
      font: "inter",
      codeTheme: "github",
    },
    previewColors: {
      primary: "#2563eb",
      background: "#ffffff",
      card: "#f8fafc",
      foreground: "#0f172a",
      border: "#e2e8f0",
      muted: "#64748b",
      badgeBg: "#f1f5f9",
    },
  },
  {
    id: "sand-light",
    name: "Warm Editorial Light",
    description:
      "Soft cream paper background with amber accents and elegant font styling.",
    mode: "light",
    settings: {
      accentColor: "amber",
      baseColor: "sand",
      radius: 0.5,
      font: "raleway",
      codeTheme: "solarized",
    },
    previewColors: {
      primary: "#d97706",
      background: "#fdfbf7",
      card: "#f7f2ea",
      foreground: "#292524",
      border: "#e7dfd5",
      muted: "#78716c",
      badgeBg: "#eee7dc",
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    description:
      "Comfortable pastel lavender palette with soothing mauve harmonies and soft rounded curves.",
    mode: "light",
    settings: {
      accentColor: "violet",
      baseColor: "cream",
      radius: 0.75,
      font: "figtree",
      codeTheme: "catppuccin",
    },
    previewColors: {
      primary: "#8839ef",
      background: "#eff1f5",
      card: "#e6e9ef",
      foreground: "#4c4f69",
      border: "#ccd0da",
      muted: "#6c6f85",
      badgeBg: "#dce0e8",
    },
  },
  {
    id: "everforest-meadow",
    name: "Everforest Meadow",
    description:
      "Serene natural sage & warm cream backdrop with fresh emerald tones and clean Outfit typography.",
    mode: "light",
    settings: {
      accentColor: "emerald",
      baseColor: "sage",
      radius: 0.5,
      font: "outfit",
      codeTheme: "everforest",
    },
    previewColors: {
      primary: "#10b981",
      background: "#fdf6e3",
      card: "#f4f0d9",
      foreground: "#2d353b",
      border: "#e0dcbd",
      muted: "#708075",
      badgeBg: "#eae4c9",
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Warm Retro",
    description:
      "Iconic parchment warmth paired with earthy orange accents and retro geometric styling.",
    mode: "light",
    settings: {
      accentColor: "orange",
      baseColor: "paper",
      radius: 0.375,
      font: "jetbrains-mono",
      codeTheme: "gruvbox",
    },
    previewColors: {
      primary: "#d65d0e",
      background: "#fbf1c7",
      card: "#f2e5bc",
      foreground: "#3c3836",
      border: "#d5c4a1",
      muted: "#7c6f64",
      badgeBg: "#ebdbb2",
    },
  },
  {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn",
    description:
      "Delicate warm sand canvas with vintage rosewood & blush pink highlights.",
    mode: "light",
    settings: {
      accentColor: "rose",
      baseColor: "dusk",
      radius: 0.75,
      font: "dm-sans",
      codeTheme: "rose-pine",
    },
    previewColors: {
      primary: "#d7827e",
      background: "#faf4ed",
      card: "#f2e9de",
      foreground: "#575279",
      border: "#dfdad9",
      muted: "#797593",
      badgeBg: "#ebe5df",
    },
  },
  {
    id: "one-light-studio",
    name: "One Light Studio",
    description:
      "Clean Atom-inspired studio light theme with vivid cyan and indigo token balance.",
    mode: "light",
    settings: {
      accentColor: "indigo",
      baseColor: "zinc",
      radius: 0.5,
      font: "geist-sans",
      codeTheme: "one-dark-pro",
    },
    previewColors: {
      primary: "#4078f2",
      background: "#fafafa",
      card: "#ffffff",
      foreground: "#383a42",
      border: "#e5e5e6",
      muted: "#696c77",
      badgeBg: "#f0f0f1",
    },
  },
  {
    id: "kanagawa-lotus",
    name: "Kanagawa Lotus",
    description:
      "Traditional Japanese paper aesthetic with wisteria violet accents and tranquil harmony.",
    mode: "light",
    settings: {
      accentColor: "purple",
      baseColor: "paper",
      radius: 0.5,
      font: "noto-sans",
      codeTheme: "kanagawa",
    },
    previewColors: {
      primary: "#624c7e",
      background: "#f2ecde",
      card: "#e7e0cf",
      foreground: "#43436c",
      border: "#d5ccba",
      muted: "#716e61",
      badgeBg: "#ded6c4",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    description:
      "Ethan Schoonover's scientifically crafted low-strain solarized light palette.",
    mode: "light",
    settings: {
      accentColor: "teal",
      baseColor: "paper",
      radius: 0.375,
      font: "roboto",
      codeTheme: "solarized",
    },
    previewColors: {
      primary: "#2aa198",
      background: "#fdf6e3",
      card: "#eee8d5",
      foreground: "#657b83",
      border: "#d7cfb9",
      muted: "#93a1a1",
      badgeBg: "#e4dcbe",
    },
  },
  {
    id: "nordic-frost-light",
    name: "Nordic Frost Light",
    description:
      "Crisp glacial slate canvas with arctic frost cyan accents and sharp modern typography.",
    mode: "light",
    settings: {
      accentColor: "cyan",
      baseColor: "nordic",
      radius: 0.375,
      font: "inter",
      codeTheme: "nord",
    },
    previewColors: {
      primary: "#0891b2",
      background: "#f8fafc",
      card: "#ffffff",
      foreground: "#0f172a",
      border: "#e2e8f0",
      muted: "#64748b",
      badgeBg: "#e0f2fe",
    },
  },
  {
    id: "vitesse-light",
    name: "Vitesse Clean Light",
    description:
      "Anthony Fu's ultra-minimal monochrome light aesthetic with fresh forest sage accents.",
    mode: "light",
    settings: {
      accentColor: "green",
      baseColor: "neutral",
      radius: 0.25,
      font: "geist-sans",
      codeTheme: "vitesse",
    },
    previewColors: {
      primary: "#1e754f",
      background: "#ffffff",
      card: "#f8fafc",
      foreground: "#18181b",
      border: "#e4e4e7",
      muted: "#71717a",
      badgeBg: "#f4f4f5",
    },
  },
  {
    id: "cyber-light",
    name: "Cyberpunk Light",
    description:
      "High-energy light theme with vivid fuchsia neon accents on clean zinc.",
    mode: "light",
    settings: {
      accentColor: "fuchsia",
      baseColor: "zinc",
      radius: 0.25,
      font: "jetbrains-mono",
      codeTheme: "synthwave-84",
    },
    previewColors: {
      primary: "#c026d3",
      background: "#ffffff",
      card: "#faf5ff",
      foreground: "#18181b",
      border: "#f0abfc",
      muted: "#71717a",
      badgeBg: "#fae8ff",
    },
  },
];

export function getPreset(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}
